### ISSUE TITLE
Create examples for hikari's Tanjun and discord.py

### ISSUE THREAD

**Issue by thenishantsapkota** [vicky5124/lavasnek_rs#12]
Would be helpful if example for Tanjun command handler was added.

**Comment by zykrah** [comment]
It should be pretty simple, should be able to just translate the lightbulb example over. If I also knew tanjunb I would do it.

**Comment by vicky5124** [comment]
On another note, there should also be a d.py example.

- [x] discord.py example. (Self Assigned)
- [x] Tanjun example. (@Jonxslays)

Will work on d.py after #9
