### ISSUE TITLE
Typing

### ISSUE THREAD

**Issue by LEv145** [vicky5124/lavasnek_rs#24]
`__init__.pyi`:
```py
...
class ConnectionInfo:
    guild_id: int
    channel_id: int
    endpoint: int
    token: str
    session_id: str
...
```
But real type is dict
![изображение](https://user-images.githubusercontent.com/40071054/154087568-e76c57a3-ba22-4fe9-a69f-b10df3ccfae6.png)

Maybe you meant an object, but you made a dictionary
If you want dict, you can use `TypedDict`

```
poetry add typing_extensions
```
```py
from typing_extensions import TypedDict

...
class ConnectionInfo(TypedDict):
    guild_id: int
    channel_id: int
    endpoint: int
    token: str
    session_id: str
```

**Comment by vicky5124** [comment]
Fixed on 939a3e1
